name: Test Swift 5.9

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    container: swift:5.9
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
